/*
Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
class Problem2{
	public static void fibonacci(){
		int a=0,b=1,c=0,sum=0;
		while(c<4000000){
			c=a+b;
			if(c%2==0)
				sum=sum+c;
			a=b;
			b=c;
		}
		System.out.println("Sum is:-"+sum);
	}
	public static void main(String args[]){
		fibonacci();
	}
}